Use working-directory instead of cd-ing Add checking if the test passed or failed

diff --git a/.github/actions/run-test/action.yaml b/.github/actions/run-test/action.yaml
--- a/.github/actions/run-test/action.yaml
+++ b/.github/actions/run-test/action.yaml
@@ -15,22 +15,40 @@ runs:
   steps:
     - name: Clone IP
       shell: bash
-      run: git clone ${{ inputs.url }} $HOME/work/${{ inputs.name }}
+      run: git clone ${{ inputs.url }} /home/runner/work/${{ inputs.name }}
     - name: Check out repository code
       uses: actions/checkout@v4
+    - name: Copy EF_UVM ot verify/uvm-python (workaround)
+      shell: bash
+      run: cp -r $(pwd) /home/runner/work/${{ inputs.name }}/verify/uvm-python/
     - name: Run Test
       shell: bash
       run: |
-        echo $(pwd)
-        ls
-        cp -r $(pwd) $HOME/work/${{ inputs.name }}/verify/uvm-python/
-        cd $HOME/work/${{ inputs.name }}/verify/uvm-python
-        echo $(pwd)
-        ls
         for test in ${{ inputs.test-names }}; do
           echo "Running Test $test"
           make run_$test
         done
+    - name: Check for test results in run
+      shell: bash
+      working-directory: /home/runner/work/${{ inputs.name }}/verify/uvm-python
+      run: |
+        passed_count=$(find sim/default_tag -type f -name 'passed' | wc -l)
+        failed_count=$(find sim/default_tag -type f -name 'failed' | wc -l)
+        unknown_count=$(find sim/default_tag -type f -name 'unknown' | wc -l)
+
+        echo "Passed: $passed_count"
+        echo "Failed: $failed_count"
+        echo "Unknown: $unknown_count"
+
+        if [ "$passed_count" -eq 0 ]; then
+          echo "Error: No passed test results found"
+          exit 1
+        elif [ "$failed_count" -ne 0 ] || [ "$unknown_count" -ne 0 ]; then
+          echo "Error: There are failed or unknown test results"
+          exit 1
+        else
+          echo "All tests passed successfully"
+        fi
 
 
 
